// design/gen-us-map.mjs
// One-shot: convert us-atlas Albers-USA states TopoJSON -> inline SVG paths.
// Output: design/us-states.js  (US_VIEWBOX + US_STATES=[{a,d}])
// Run: node design/gen-us-map.mjs  (expects /tmp/states-albers.json)

import { readFileSync, writeFileSync } from 'node:fs';
import { feature } from 'topojson-client';

const FIPS = {
  '01':'AL','02':'AK','04':'AZ','05':'AR','06':'CA','08':'CO','09':'CT','10':'DE','11':'DC','12':'FL',
  '13':'GA','15':'HI','16':'ID','17':'IL','18':'IN','19':'IA','20':'KS','21':'KY','22':'LA','23':'ME',
  '24':'MD','25':'MA','26':'MI','27':'MN','28':'MS','29':'MO','30':'MT','31':'NE','32':'NV','33':'NH',
  '34':'NJ','35':'NM','36':'NY','37':'NC','38':'ND','39':'OH','40':'OK','41':'OR','42':'PA','44':'RI',
  '45':'SC','46':'SD','47':'TN','48':'TX','49':'UT','50':'VT','51':'VA','53':'WA','54':'WV','55':'WI','56':'WY'
};

const topo = JSON.parse(readFileSync('/tmp/states-albers.json', 'utf8'));
const fc = feature(topo, topo.objects.states);

let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
const ring = (r) => {
  let s = '';
  for (let i = 0; i < r.length; i++) {
    const x = r[i][0], y = r[i][1];
    if (x < minX) minX = x; if (x > maxX) maxX = x; if (y < minY) minY = y; if (y > maxY) maxY = y;
    s += (i ? 'L' : 'M') + x.toFixed(1) + ' ' + y.toFixed(1);
  }
  return s + 'Z';
};
const geomPath = (g) => {
  const c = g.coordinates;
  if (g.type === 'Polygon') return c.map(ring).join('');
  if (g.type === 'MultiPolygon') return c.map((p) => p.map(ring).join('')).join('');
  return '';
};

const states = [];
for (const f of fc.features) {
  const a = FIPS[f.id];
  if (!a) continue; // skip territories
  states.push({ a, d: geomPath(f.geometry) });
}

const pad = 6;
const vb = `${(minX - pad).toFixed(0)} ${(minY - pad).toFixed(0)} ${(maxX - minX + pad * 2).toFixed(0)} ${(maxY - minY + pad * 2).toFixed(0)}`;

const out =
  `// Generated by gen-us-map.mjs from us-atlas (public domain). Albers USA projection.\n` +
  `export const US_VIEWBOX = ${JSON.stringify(vb)};\n` +
  `export const US_STATES = ${JSON.stringify(states)};\n`;
writeFileSync(new URL('./us-states.js', import.meta.url), out);
console.log(`Wrote us-states.js — ${states.length} states, viewBox "${vb}", ${(out.length / 1024).toFixed(0)} KB`);
